source 'https://github.com/CocoaPods/Specs.git'

target 'Wabbly', :exclusive => true do
  pod "Wabbly", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Wabbly", :path => "../"

  
end
