# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
# podfile: Example/Podfile
before_install: cd Example && pod install && cd -
script:
- xctool test -workspace Example/Wabbly.xcworkspace -scheme Wabbly-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
